steps:
    - uses: actions/checkout@v4

    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-cache

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build EXE
      run: npm run build

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: GPT-EXE
        path: dist/*.exe
